name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - "manifests/**"
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - "manifests/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/ryannoblett/octank
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - 
        name: Checkout repo
        uses: actions/checkout@v2
      - 
        name: Get Commit SHA
        id: sha
        run: |
          echo "::set-output name=commit-sha::$(git rev-parse --short "$GITHUB_SHA")\n"
      - 
        name: Update image tag
        run: |
          sed -i manifests/deployment.yaml -e "s/octank:.*/octank:${{ steps.sha.outputs.commit-id }}/"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Ryan Noblett
          author_email: ryan.noblett@gmail.com
          message: Deployed tag ${{ steps.sha.outputs.commit-id }}
          add: metadata/deployment.yaml
